version: '3.7'

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: askme_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=askme
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=1234

  nginx:
    image: nginx:1.23.3
    container_name: askme_nginx
    volumes:
      - ./askme.conf:/etc/nginx/conf.d/askme.conf
      - ./static:/static
      - ./uploads:/uploads
#    ports:
#      - "80:80"
#      - "443:443"
    network_mode: host
